project:
  type: website
  output-dir: docs

website:
  title: "aldairperez.io"
  image: <img src="C:\Users\aldai\Git\aldairperez.github.io\docs\resources\Screenshot 2024-08-22 143640.png">
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

about:
  template: trestles
