project:
  type: website
  output-dir: docs

website:
  title: "aldairperez.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

about:
  template: trestles

  page-footer:
    background: light # or 'dark'
    left: Aldair Perez Marmolejo
    right: Spring 2025

    theme: styles.scss # I've also removed the 'css: styles.css' option that was included by the default, since I'll be writing all my sass and css in this single styles.scss file
