project:
  type: website
  output-dir: docs

website:
  title: "aldairperez.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: About
      - href: resume.qmd
        text: resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

about:
  template: trestles
