---
title: Aldair Perez
---

Hello, I'm Aldair Perez and I'm a CSU undergraduate student majoring in ESS. I'm in my senior year, and I graduate this May. What I'm interested in is the future of sustainability of our world, such as adopting cleaner energy/fuel and development of our society. I have learned about systems thinking, the ecological aspect of our planet, e-waste, and math courses to improve my knowledge. I worked on group projects, such as talking about nuclear energy and if corporations are blamed for environmental degradation, that not only helps me learn and discuss these real-world issues, but it helped me become a productive team member when working in a group setting. I have written some essays in regard to electric vehicles, where I mentioned about the environmental impact and whether or not EVs will be a solution towards reducing our carbon footprint.

Hopefully, this source helps readers understand my reason for having ESS as my major and the kind of work and thinking I've done in my college years.

aldairperez864\@gmail.com
